# Generated by Django 5.2.1 on 2025-06-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
