# Generated by Django 5.2.1 on 2025-06-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_car_type_car_model_year_car_transmission_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='available',
            new_name='availability',
        ),
    ]
